"""empty message

Revision ID: 518721aa2bef
Revises: 459f36b9a1ed
Create Date: 2023-01-23 13:44:31.915431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518721aa2bef'
down_revision = '459f36b9a1ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
